### ISSUE TITLE
Customizable app name for the notification

### ISSUE THREAD

**Issue by YuriyLisovskiy** [MaliciousFiles/WinToaster#2]
I'm unable to customize the app name of the toast notification, it always shows "Python".
I'd like to have the possibility to set an app name parameter:
```python
toast = win_toaster.create_toast(
    app_name="My app",
    title="My title",
    msg="My message"
)
```
Is it possible to implement this feature in your module?

**Comment by MaliciousFiles** [comment]
Hello YuriyLisovskiy,

It has been a while since I wrote the code for this module, but I believe this was a feature I was looking for a way to implement then, and couldn't figure it out.

However, at some point I'm looking to completely overhaul the backend of WinToaster, allowing you to implement buttons and more. I will see if I can make it happen then, but for now I don't know how.

You are, of course, free to poke around the code yourself (it's all in Python).

-MaliciousFiles

P.S: if I may ask, what are you using this in? I always love to see people using my products.

**Comment by YuriyLisovskiy** [comment]
I've created a tiny module for multi-platform notifications named [`py-notifier`](https://github.com/YuriyLisovskiy/pynotifier) and I used `WinToaster` for Windows. If you remember, you made a pull request to replace the [`win10toast`](https://github.com/jithurjacob/Windows-10-Toast-Notifications) dependency with `WinToaster` in my module some time ago 🙂
